name: badges_bar
version: 0.1.5
description: >
  SVG badge generator for packages on pub.dev. Likes, pub points and popularity.
homepage: https://github.com/bruno-garcia/badges.bar

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  http: ^0.12.2
  sentry: ^4.0.5

dev_dependencies:
  test: ^1.15.4
  test_coverage: ^0.4.3
  pedantic: ^1.9.2
